directory/urls.py
from django.conf.urls import url #4
from django.core.urlresolvers import reverse

from . import views #4

urlpatterns = [ #4
    url(r'^providers/(?P<provider_pk>\d+)/(?P<driver_pk>\d+)/$', views.driver_detail, name='driver_detail'),
    url(r'^providers/(?P<provider_pk>\d+)/edit_driver/(?P<driver_pk>\d+)/$', views.edit_driver, name='edit_driver'),
    url(r'^providers/(?P<provider_pk>\d+)/add_driver/$', views.add_driver, name='add_driver'),
    url(r'^providers/(?P<provider_pk>\d+)/$', views.provider_detail, name='provider_detail'),
    url(r'^providers/add_provider/$', views.add_provider, name='add_provider'),
    url(r'^providers/edit_provider/(?P<provider_pk>\d+)/$', views.edit_provider, name='edit_provider'),
    url(r'^trainings/firstaidcpr/$', views.firstaid_list, name='firstaid_list'),
    url(r'^trainings/defensive_driving/$', views.ddriving_list, name='ddriving_list'),
    url(r'^trainings/pass/$', views.pass_list, name='pass_list'),
    url(r'^drivers/$', views.driver_list, name='driver_list'),
    url(r'^trainings/$', views.training_nav, name='training_nav'),
    url(r'^providers/$', views.provider_list, name='provider_list'),
    url(r'^user_profile/$', views.user_profile, name='user_profile'),
    url(r'^login/$', views.login, name='login'),
    url(r'^$', views.dashboard, name='dashboard'), #4
] #4

    # url(r'(?P<provider_pk>\d+)/(?P<driver_pk>\d+)/$', views.driver_detail, name='driver_detail'),

provider_crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns #5

from directory.models import Provider

from . import views #2

urlpatterns = [
    url(r'^directory/', include('directory.urls', namespace='directory')), #5
    url(r'^admin/', admin.site.urls),
    url(r'^issues/$', views.issue_view, name='issue'), #form
    url(r'^$', views.project_intro, name='home'), #2
]

urlpatterns += staticfiles_urlpatterns() #5

directory/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Provider(models.Model):
    business_name = models.CharField(max_length=56)
    address = models.CharField(max_length=56)
    phone_number = models.IntegerField()
    business_license = models.CharField(max_length=18)
    notes = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    # created_by = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.business_name

    def get_absolute_url(self):
        return reverse('directory:provider_detail', kwargs={
            'provider_pk': self.id,
    })

class Contract(models.Model):
    provider = models.ForeignKey(Provider)
    contract = models.FileField(upload_to='provider_contracts')
    start_date = models.DateField()
    end_date = models.DateField()

class Driver(models.Model):
    provider = models.ForeignKey(Provider)
    first_name = models.CharField(max_length=56)
    last_name = models.CharField(max_length=56)
    driver_id = models.CharField(max_length=12)
    birth_date = models.DateField()
    hire_date = models.DateField()
    eligible = models.BooleanField(default=False)
    license = models.CharField(max_length=12)
    notes = models.TextField(blank=True, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    # created_by = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    def get_absolute_url(self):
        return reverse('directory:driver_detail', kwargs={
            'provider_pk': self.provider_id,
            'driver_pk': self.id
    })

    class Meta:
        ordering = ['first_name', 'last_name', ]

class Provider_Contact(models.Model):
    company = models.ForeignKey(Provider)
    first_name = models.CharField(max_length=56)
    last_name = models.CharField(max_length=56)
    title = models.CharField(max_length=255)
    phone_number = models.IntegerField()
    email_address = models.EmailField()

    def __str__(self):
        return self.first_name + self.last_name

    def mailto(self):
        return '{}, {} <{}>'.format(self.first_name, self.last_name, self.email)

class Background_Check(models.Model):
    driver = models.ForeignKey(Driver)
    date_completed = models.DateField()
    date_expiring = models.DateField()
    granting_agency = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    # created_by = models.User...

class Training(models.Model):
    driver = models.ForeignKey(Driver)
    training_date = models.DateField()
    time_since = models.DurationField()
    cert_file = models.FileField(upload_to='Training_Certificates')
    granting_agency = models.CharField(max_length=255)
    instructor = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    notes = models.TextField(blank=True,default='')
    # created_by = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name

class PASS(Training):
    name = models.CharField(default="Passenger Assistance Safety and Sensitivity", max_length=255)
    expiration = models.DateField()

    def get_absolute_url(self):
        return reverse('directory:pass', kwargs={
            'driver_pk': self.driver_id,
            'pass_pk': self.id
        })

class DefensiveDriving(Training):
    name = models.CharField(default="Defensive Driving", max_length=255)
    expiration = models.DateField()

    def get_absolute_url(self):
        return reverse('directory:defensive', kwargs={
            'driver_pk': self.driver_id,
            'defensive_pk': self.id
        })

class FirstAidCPR(Training):
    name = models.CharField(default="First Aid and CPR", max_length=255)
    expiration = models.DateField()

    def get_absolute_url(self):
        return reverse('directory:firstaidcpr', kwargs={
            'driver_pk': self.driver_id,
            'firstaidcpr': self.id
        })

directory/forms.py
from django import forms

from . import models

class ProviderForm(forms.ModelForm):
    class Meta:
        model = models.Provider
        fields = [
            'business_name',
            'address',
            'phone_number',
            'business_license',
            'notes'
        ]

class DriverForm(forms.ModelForm):
    class Meta:
        model = models.Driver
        fields = [
            'first_name',
            'last_name',
            'driver_id',
            'birth_date',
            'hire_date',
            'license',
            'notes'
        ]

directory/views.py
from django.shortcuts import render, get_object_or_404

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect #3
from django.http import HttpResponse #3
from itertools import chain

from . import forms
from .models import Provider #3
from .models import Driver, PASS, DefensiveDriving, Training, FirstAidCPR

def dashboard(request):
    num_providers = len(Provider.objects.all())
    num_drivers = len(Driver.objects.all())
    return render(request, 'directory/dashboard.html', {'num_providers': num_providers,
                                                            'num_drivers': num_drivers})

def provider_list(request): #3
    providers = Provider.objects.all() #3
    # output = ', '.join([str(provider) for provider in providers]) #3
    # return HttpResponse(output) #3
    email = "capriciash@gmail.com"
    return render(request, 'directory/provider_list.html', {'providers': providers,
                                                            'email': email})

def driver_list(request):
    drivers = Driver.objects.all()
    return render(request, 'directory/driver_list.html', {'drivers': drivers})

def provider_detail(request, provider_pk):
    # provider = Provider.objects.get(pk=pk) replaced with the 404 error line below
    provider = get_object_or_404(Provider, pk=provider_pk)
    return render(request, 'directory/provider_detail.html', {'provider': provider})

def driver_detail(request, provider_pk, driver_pk):
    driver = get_object_or_404(Driver, pk=driver_pk)
    trainings = sorted(chain(driver.pass_set.all(), driver.defensivedriving_set.all()),
                key=lambda t: t.expiration)
    return render(request, 'directory/driver_detail.html', {
            'driver': driver,
            'trainings': trainings
        })

    def get_absolute_url(self):
        return reverse('directory/driver/detail.html', kwargs={'provider_pk': self.provider.pk, 'driver_pk': self.pk})

def training_nav(request):
    return render(request, 'directory/training_nav.html')

def ddriving_list(request):
    ddrivings = DefensiveDriving.objects.all()
    return render(request, 'directory/ddriving_list.html', {'ddrivings': ddrivings})

def pass_list(request):
    passes = PASS.objects.all()
    return render(request, 'directory/pass_list.html', {'passes': passes})

def firstaid_list(request):
    faids = FirstAidCPR.objects.all()
    return render(request, 'directory/firstaid_list.html', {'faids': faids})

def user_profile(request):
    return render(request, 'directory/user_profile.html')

def login(request):
    return render(request, 'directory/login.html')



@login_required
def add_driver(request, provider_pk):
    provider = get_object_or_404(Provider, pk=provider_pk)
    form = forms.DriverForm()

    if request.method == 'POST':
        form = forms.DriverForm(request.POST)
        if form.is_valid():
            driver = form.save(commit=False)
            driver.provider = provider
            driver.save()
            messages.add_message(request, messages.SUCCESS, "Driver added!")
            return HttpResponseRedirect(driver.get_absolute_url())
    return render(request, 'directory/driver_form.html', {'form': form, 'provider': provider})

@login_required
def add_provider(request):
    form = forms.ProviderForm()

    if request.method == 'POST':
        form = forms.ProviderForm(request.POST)
        if form.is_valid():
            provider = form.save()
            messages.add_message(request, messages.SUCCESS, "Provider added!")
            return HttpResponseRedirect(provider.get_absolute_url())
    return render(request, 'directory/provider_form.html', {'form': form})

@login_required
def edit_provider(request, provider_pk):
    provider = get_object_or_404(Provider, pk=provider_pk)
    form = forms.ProviderForm(instance=provider)

    if request.method == 'POST':
        form = forms.ProviderForm(instance=provider, data=request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "Updated {}".format(form.cleaned_data['business_name']))
            return HttpResponseRedirect(provider.get_absolute_url())
    return render(request, 'directory/provider_form.html', {'form': form})

@login_required
def edit_driver(request, provider_pk, driver_pk):
    driver = get_object_or_404(Driver, pk=driver_pk, provider_id=provider_pk)
    form = forms.DriverForm(instance=driver)

    if request.method == 'POST':
        form = forms.DriverForm(instance=driver, data=request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "Updated {} {}".format(form.cleaned_data['first_name'], form.cleaned_data['last_name']))
            return HttpResponseRedirect(driver.get_absolute_url())
    return render(request, 'directory/driver_form.html', {'form': form})

# def training_detail(request, driver_pk, training_pk):
#     driver = get_object_or_404(Driver, provider_id=provider_pk, pk=driver_pk)
#     trainings = sorted(chain(PASS_set.all(), DefensiveDriving_set.all()),
#                 key = lambda t: t.expiration)
#     return render(request, 'directory/driver_detail.html', {
#             'driver': driver,
#             'trainings': trainings
#             })

directory/templates/directory/dashboard.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% load contract_extras %}

{% block static %}<link rel="stylesheet" href="{% static 'directory/css/directory.css' %}">{% endblock %}

{% block title %}Dashboard{% endblock %}

{% block navbar %}
<header class="py-2 bg-secondary text-white">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1><i class="fa fa-address-book"></i> Dashboard</h1>
      </div>
    </div>
  </div>
</header>

<!-- ACTIONS -->
<section id="action" class="py-4 mb-4 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <a href="#" class="btn btn-primary btn-block" data-toggle="modal" data-target="#addProviderModal">
          <i class="fa fa-plus"></i> Add Provider
        </a>
      </div>
      <div class="col-md-3">
        <a href="#" class="btn btn-success btn-block" data-toggle="modal" data-target="#addDriverModal">
          <i class="fa fa-plus"></i> Add Driver
        </a>
      </div>
      <div class="col-md-3">
        <a href="#" class="btn btn-warning btn-block" data-toggle="modal" data-target="#addUserModal">
          <i class="fa fa-plus"></i> Add User
        </a>
      </div>
    </div>
  </div>
</section>

<!-- PROVIDER MODAL -->
<div class="modal fade" id="addProviderModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-primary text-white">
        <h5 class="modal-title">Add Provider</h5>
        <button class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control">
          </div>
          <div class="form-group">
            <label for="mode">Mode</label></br>
            <label class="checkbox-inline">
              <input type="checkbox" value="sedan"> Sedan
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" value="wheelchair"> Weelchair
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" value="stretcher"> Stretcher
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" value="secure"> Secure
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" value="ambulance"> Ambulance
            </label>
          </div>
          <div class="form-group">
            <label for="contract">Upload Contract</label>
            <input type="file" class="form-control-file">
            <small class="form-text text-muted">Max Size 3 mb</small>
          </div>
          <div class="form-group">
            <label for="notes">Notes</label>
            <textarea class="form-control"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button class="btn btn-primary" data-dismiss="modal">Save & Submit</button>
      </div>
    </div>
  </div>
</div>

<!-- DRIVER MODAL -->
<div class="modal fade" id="addDriverModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-success text-white">
        <h5 class="modal-title">Add Driver</h5>
        <button class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="fname">First Name</label>
            <input type="text" class="form-control">
          </div>
          <div class="form-group">
            <label for="lname">Last Name</label>
            <input type="text" class="form-control">
          </div>
          <div class="form-group">
            <label for="license">License Number</label>
            <input type="text" class="form-control">
          </div>
          <div class="form-group">
            <label for="bday">Birthday</label>
            <input type="date" name="bday">
          </div>
          <div class="form-group">
            <label for="mode">Mode</label></br>
            <label class="checkbox-inline">
              <input type="checkbox" value="sedan"> Sedan
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" value="wheelchair"> Wheelchair
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" value="stretcher"> Stretcher
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" value="secure"> Secure
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" value="ambulance"> Ambulance
            </label>
          </div>
          <div class="form-group">
            <label for="hiredate">Date of Hire</label>
            <input type="date" name="hiredate">
          </div>
          <div class="form-group">
            <label for="notes">Notes</label>
            <textarea class="form-control"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button class="btn btn-success" data-dismiss="modal">Save & Submit</button>
      </div>
    </div>
  </div>
</div>

<!-- TRAINING MODAL -->
<div class="modal fade" id="addUserModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-warning text-white">
        <h5 class="modal-title">Add User</h5>
        <button class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control">
          </div>
          <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control">
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control">
          </div>
          <div class="form-group">
            <label for="name">Confirm Password</label>
            <input type="password" class="form-control">
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button class="btn btn-warning" data-dismiss="modal">Save & Submit</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}

<!-- POSTS -->
<section id="dir_dashboard">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <div class="card">
          <div class="card-header">
            <h4>Providers</h4>
          </div>
          <table class="table table-striped">
            <thead class="thead-inverse">
              <tr>
                <th>#</th>
                <th>Provider Name</th>
                <th>Address</th>
                <th>Phone Number</th>
                <th>Number of Drivers</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td scope="row">1</td>
                <td>Name 1</td>
                <td>123 Something St</td>
                <td>555-555-5555</td>
                <td>23</td>
                <td><a href="provdetail.html" class="btn btn-secondary">
                  <i class="fa fa-angle-double-right"></i> Details
                </a></td>
              </tr>
              <tr>
                <td scope="row">1</td>
                <td>Name 2</td>
                <td>123 Something St</td>
                <td>555-555-5555</td>
                <td>2</td>
                <td><a href="provdetail.html" class="btn btn-secondary">
                  <i class="fa fa-angle-double-right"></i> Details
                </a></td>
              </tr>
              <tr>
                <td scope="row">1</td>
                <td>Name 3</td>
                <td>123 Something St</td>
                <td>555-555-5555</td>
                <td>972</td>
                <td><a href="provdetail.html" class="btn btn-secondary">
                  <i class="fa fa-angle-double-right"></i> Details
                </a></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card text-center bg-primary text-white mb-3">
          <div class="card-body">
            <h4>Providers</h4>
            <h1 class="display-5">
              <i class="fa fa-address-book"></i> {{ num_providers }}
            </h1>
            <a href="{% url 'directory:provider_list' %}" class="btn btn-outline-light btn-sm">
              Manage
            </a>
          </div>
        </div>
        <div class="card text-center bg-success text-white mb-3">
          <div class="card-body">
            <h4>Drivers</h4>
            <h1 class="display-5">
              <i class="fa fa-drivers-license"></i> {{ num_drivers }}
            </h1>
            <a href="{% url 'directory:driver_list' %}" class="btn btn-outline-light btn-sm">
              Manage
            </a>
          </div>
        </div>
        <div class="card text-center bg-warning text-white mb-3">
          <div class="card-body">
            <h4>Trainings</h4>
            <h1 class="display-5">
              <i class="fa fa-pencil"></i> 942
            </h1>
            <a href="{% url 'directory:training_nav' %}" class="btn btn-outline-light btn-sm">
              Manage
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

directory/templates/directory/driver_detail.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block static %}<link rel="stylesheet" href="{% static 'directory/css/directory.css' %}">{% endblock %}

{% block title %}{{ driver }}{% endblock %}

{% block navbar %}
<!-- STRIPE -->
<header class="py-2 bg-success text-white">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1><i class="fa fa-drivers-license"></i> Driver - {{ driver }}</h1>
      </div>
    </div>
  </div>
</header>

<!-- BUTTONS -->
<section class="py-4 mb-4 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
          <a href="{% url 'directory:edit_driver' provider_pk=driver.provider.pk driver_pk=driver.id %}" class="btn btn-success btn-block">
            <i class="fa fa-edit"></i> Edit Driver
          </a>
        </div>
      <div class="col-md-6 ml-auto">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search">
          <span class="input-group-btn">
            <button class="btn btn-success">Search</button>
          </span>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

{% block content %}
<section>
  <div class="container">
  {% with fir=driver.first_name %}
    <h2>{{ driver.first_name }} {{ driver.last_name }}</h2>
    <h3># {{ driver.driver_id }}</h3>
    <p>Birthdate: {{ driver.birth_date }}</p>
    <p>Date of Hire: {{ driver.hire_date }}</p>
    <p>Company: <a href="{% url 'directory:provider_detail' provider_pk=driver.provider.pk %}">
              {{ driver.provider.business_name }}</a></p>
    <p>Notes:{{ driver.notes|linebreaks }} ({{ driver.notes|wordcount }} words.)</p>
    <p>Trainings:</p>
    <ul>
    {% for training in trainings %}
      <li>{{ training.name }} - {{ training.training_date }} to {{ training.expiration }}</li>
    {% endfor %}
    </ul>
  {% endwith %}
  </div>
</section>
{% endblock %}

directory/templates/directory/provider_detail.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% load humanize %}

{% block static %}<link rel="stylesheet" href="{% static 'directory/css/directory.css' %}">{% endblock %}

{% block title %} {{ provider.business_name }} {% endblock title %}

{% block navbar %}
<!-- STRIPE -->
<header class="py-2 bg-primary text-white">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1><i class="fa fa-address-book"></i> Provider - {{ provider.business_name }}</h1>
      </div>
    </div>
  </div>
</header>

<!-- BUTTONS -->
<section class="py-4 mb-4 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        {% if user.is_authenticated %}
          <a href="{% url 'directory:edit_provider' provider_pk=provider.id %}" class="btn btn-primary btn-block">
            <i class="fa fa-edit"></i> Edit Provider
          </a>
        {% endif %}
      </div>
      <div class="col-md-6 ml-auto">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search">
          <span class="input-group-btn">
            <button class="btn btn-primary">Search</button>
          </span>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

{% block content %}
<div class="container">
  <article>
    <h3>Address</h3>
    <p>{{ provider.address }}</p>
    <h3>Contracts</h3>
    <ul>
    {% for contract in provider.contract_set.all %}
      <li>{{ contract.start_date|date:"m/d/Y" }} - {{ contract.end_date|date:"m/d/Y" }}</li>
    {% endfor %}
    </ul>
    <h3>Drivers</h3>
      <p>This provider has {{ provider.driver_set.count|apnumber }} driver{{ provider.driver_set.count|pluralize }}:
        {{ provider.driver_set.all|join:", " }}</p>
      <ul>
      {% for driver in provider.driver_set.all %}
        <li>
          <a href="{% url 'directory:driver_detail' provider_pk=provider.pk driver_pk=driver.pk %}">
            {{ driver.first_name }} {{ driver.last_name}} - {{ driver.driver_id }}
          </a>
        </li>
      {% endfor %}
    </ul>
  </article>
  {% if user.is_authenticated %}
  <a href="{% url 'directory:add_driver' provider_pk=provider.pk %}" class="button">Add New Driver</a>
  {% endif %}
</div>
{% endblock content %}

directory/templates/directory/training_nav.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% load contract_extras %}

{% block static %}<link rel="stylesheet" href="{% static 'directory/css/directory.css' %}">{% endblock %}

{% block title %}Trainings{% endblock %}

{% block navbar %}
<!-- STRIPE -->
<header class="py-2 bg-warning text-white">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1><i class="fa fa-pencil"></i> Trainings</h1>
      </div>
    </div>
  </div>
</header>

<!-- BUTTONS -->
<section class="py-4 mb-4 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
          <a href="#" class="btn btn-warning btn-block" data-toggle="modal" data-target="#newTrainingModal">
            <i class="fa fa-plus"></i> Add Training Record
          </a>
        </div>
      <div class="col-md-6 ml-auto">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search">
          <span class="input-group-btn">
            <button class="btn btn-warning">Search</button>
          </span>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- TRAINING MODAL -->
<div class="modal fade" id="newTrainingModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-warning text-white">
        <h5 class="modal-title">Add Training Record</h5>
        <button class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control">
          </div>
          <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control">
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control">
          </div>
          <div class="form-group">
            <label for="name">Confirm Password</label>
            <input type="password" class="form-control">
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button class="btn btn-warning" data-dismiss="modal">Save & Submit</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<section>
  <div class="container">
    <!-- PASS TABLE -->
    <div class="row">
      <div class="col-md-4">
        <h3><a href="{% url 'directory:pass_list' %}">PASS</a></h3>
        <table class="table table-hover">
          <thead class="thead-default">
            <tr>
              <th>Driver</th>
              <th>Days to Expiration</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Name</td>
              <td>4</td>
            </tr>
          </tbody>
        </table>
      </div>
    <!-- DEFENSIVE DRIVING TABLE -->
      <div class="col-md-4">
        <h3><a href="{% url 'directory:ddriving_list' %}">Defensive Driving</a></h3>
        <table class="table table-hover">
          <thead class="thead-default">
            <tr>
              <th>Driver</th>
              <th>Days to Expiration</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Name</td>
              <td>72</td>
            </tr>
          </tbody>
        </table>
      </div>
    <!-- FIRST AID / CPR TABLE-->
      <div class="col-md-4">
        <h3><a href="{% url 'directory:firstaid_list' %}">FIRST AID / CPR</a></h3>
        <table class="table table-hover">
          <thead class="thead-default">
            <tr>
              <th>Driver</th>
              <th>Days to Expiration</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Name</td>
              <td>1</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>
{% endblock %}