directory/urls.py
from django.conf.urls import url #4
from django.core.urlresolvers import reverse

from . import views #4

urlpatterns = [ #4
    url(r'^providers/(?P<provider_pk>\d+)/(?P<driver_pk>\d+)/$', views.driver_detail, name='driver_detail'),
    url(r'^providers/(?P<provider_pk>\d+)/edit_driver/(?P<driver_pk>\d+)/$', views.edit_driver, name='edit_driver'),
    url(r'^providers/(?P<provider_pk>\d+)/add_driver/$', views.add_driver, name='add_driver'),
    url(r'^providers/(?P<provider_pk>\d+)/$', views.provider_detail, name='provider_detail'),
    url(r'^providers/add_provider/$', views.add_provider, name='add_provider'),
    url(r'^providers/edit_provider/(?P<provider_pk>\d+)/$', views.edit_provider, name='edit_provider'),
    url(r'^trainings/firstaidcpr/$', views.firstaid_list, name='firstaid_list'),
    url(r'^trainings/defensive_driving/$', views.ddriving_list, name='ddriving_list'),
    url(r'^trainings/pass/$', views.pass_list, name='pass_list'),
    url(r'^drivers/$', views.driver_list, name='driver_list'),
    url(r'^trainings/$', views.training_nav, name='training_nav'),
    url(r'^providers/$', views.provider_list, name='provider_list'),
    url(r'^user_profile/$', views.user_profile, name='user_profile'),
    url(r'^login/$', views.login, name='login'),
    url(r'^$', views.dashboard, name='dashboard'), #4
] #4

    # url(r'(?P<provider_pk>\d+)/(?P<driver_pk>\d+)/$', views.driver_detail, name='driver_detail'),

provider_crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns #5

from directory.models import Provider

from . import views #2

urlpatterns = [
    url(r'^directory/', include('directory.urls', namespace='directory')), #5
    url(r'^admin/', admin.site.urls),
    url(r'^issues/$', views.issue_view, name='issue'), #form
    url(r'^$', views.project_intro, name='home'), #2
]

urlpatterns += staticfiles_urlpatterns() #5

templates/home.html
{% extends "layout.html" %}
{% block title %}Welcome!{% endblock %}

{% block content %}
<h1>Welcome to this site.</h1>
{% endblock %}

templates/issue_form.html
{% extends "layout.html" %}

{% block title %}Report an Issue{% endblock %}

{% block navbar %}
<header class="py-2 bg-danger text-white mb-4">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1><i class="fa fa-comment"></i> Report an Issue</h1>
      </div>
    </div>
  </div>
</header>
{% endblock %}

{% block content %}
<div class="site-container">
  {% if messages %}
    <div class="row justify-content-center">
      {% for message in messages %}
        <div data-alert class="alert alert-success">
          {{ message }}
          <a href="#" class="close" data-dismiss="alert">&times;</a>
        </div>
      {% endfor %}
    </div>
  {% endif %}
  <div class="row">
    <form action="" method="POST">
      {{ form.as_p }}
      <!-- to validate that data is being submitted to local site -->
      {% csrf_token %}
      <input type="submit" class="button btn btn-secondary">
    </form>
  </div>
</div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
{% load contract_extras %}

<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block static %}{% endblock %}
  </head>
  <body>

    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
      <div class="container">
        <a href="{% url 'home' %}" class="navbar-brand" >Transportation Directory</a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item px-2">
              <a href="{% url 'directory:dashboard' %}" class="nav-link">Dashboard</a>
            </li>
            <li class="nav-item px-2">
              <a href="{% url 'directory:provider_list' %}" class="nav-link">Providers</a>
            </li>
            <li class="nav-item px-2">
              <a href="{% url 'directory:driver_list' %}" class="nav-link">Drivers</a>
            </li>
            <li class="nav-item px-2">
              <a href="{% url 'directory:training_nav' %}" class="nav-link">Training</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown mr-3">
              <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-user"></i> Welcome User!
              </a>
              <div class="dropdown-menu">
                <a href="profile.html" class="dropdown-item">
                  <i class="fa fa-user-circle"></i> Profile
                </a>
                <a href="settings.html" class="dropdown-item">
                  <i class="fa fa-gear"></i> Settings
                </a>
                <a href="{% url 'issue' %}" class="dropdown-item">
                  <i class="fa fa-comment"></i> Report an Issue
                </a>
              </div>
            </li>
            <li class="nav-item">
              <a href="login.html" class="nav-link">
                <i class="fa fa-user-times"></i> Logout
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- SECOND NAVBAR -->
    {% block navbar %}{% endblock %}

    <!-- SITE -->
    {% if messages %}
      <div class="row justify-content-center">
        {% for message in messages %}
          <div data-alert class="alert alert-success">
            {{ message }}
            <a href="#" class="close" data-dismiss="alert">&times;</a>
          </div>
        {% endfor %}
      </div>
    {% endif %}
    
    {% block content %}{% endblock %}

    <!-- FOOTER -->
    <footer id="main-footer" class="bg-dark text-white mt-5 p-2 sticky-bottom">
      <div class="container">
        <div class="row">
          <div class="col">
            <p class="lead text-center">Created by Ashley Riehl</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>